### ISSUE TITLE
moving development forward

### ISSUE THREAD

**Issue by kenany** [dwaite/wintersmith-markdown-it#6]
@dwaite, any interest in merging the existing PRs? Looks like they've been sitting around for over a year now, and they all look like useful additions to the plugin.

Furthermore, would you be open to adding some collaborators/owners to the repo and on npm? I can't speak for others, like @alexkwolfe and @lhagan, but it shouldn't hurt to add all of us to lighten the workload for yourself :)

**Comment by dwaite** [comment]
I'd be for transferring the project to someone else who wants to take a more active role, and/or adding participants.

In the meantime, I've merged the current pull requests (with a few changes). To be honest, I don't get notifications for projects in this domain, so I had no idea I had pending pull requests!
