### ISSUE TITLE
Cannot enable typographer or linkify.

### ISSUE THREAD

**Issue by dlras2** [dwaite/wintersmith-markdown-it#8]
It seems like Markdown-It is always initialized with its default options, before other plugins are added. This makes it impossible to enable the built-in modules or do other kinds of specific configuration.

**Comment by dlras2** [comment]
@dwaite I have added a pull request I believe resolves this issue. Please let me know if you have any questions.

**Comment by dwaite** [comment]
Merged, thank you for your PR!

**Comment by dlras2** [comment]
@dwaite Excellent, thank you! When will this be version-bumped and available on NPM?

**Comment by dwaite** [comment]
I don’t have any other changes planned near-term, so I’ll do that right now

-DW

**Comment by dwaite** [comment]
Published as 0.1.1
